name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"   # daily (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@v0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: djbacad
          THEME: noctis_minimus
